const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),readline=require('readline');
const cfgPath=path.join(__dirname,'config.local.json');if(!fs.existsSync(cfgPath)){console.error('Стартирай първо SETUP SCRAPER.cmd');process.exit(1)}
const cfg=JSON.parse(fs.readFileSync(cfgPath,'utf8')),rl=readline.createInterface({input:process.stdin,output:process.stdout});
const ask=q=>new Promise(r=>rl.question(q,a=>r(a.trim()))),sleep=ms=>new Promise(r=>setTimeout(r,ms)),uniq=a=>[...new Set(a.filter(Boolean))];
async function api(action,opt={},token=''){let headers={...(opt.headers||{})};if(token)headers['X-D8-Auth']=token;let r=await fetch(cfg.dashboardUrl.replace(/\/$/,'')+'/api.php?action='+action,{...opt,headers}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||'Dashboard HTTP '+r.status);return d}
async function login(){return(await api('login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:cfg.username,password:cfg.password})})).authToken}
async function links(page,query,limit){let url=/^https?:\/\//i.test(query)?query:'https://www.google.com/maps/search/'+encodeURIComponent(query)+'?hl=bg';await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(3500);let consent=page.getByRole('button',{name:/accept all|приемам всички|съгласявам се/i});if(await consent.count())await consent.first().click().catch(()=>{});console.log('Ако има CAPTCHA, реши я в отворения Chrome.');await page.waitForSelector('a[href*="/maps/place/"]',{timeout:120000});let found=new Set(),still=0;while(found.size<limit&&still<8){let batch=await page.locator('a[href*="/maps/place/"]').evaluateAll(xs=>xs.map(x=>x.href));let before=found.size;batch.forEach(x=>found.add(x.split('&')[0]));still=found.size===before?still+1:0;process.stdout.write('\rНамерени: '+Math.min(found.size,limit)+'/'+limit);let feed=page.locator('[role="feed"]').first();if(await feed.count())await feed.evaluate(x=>x.scrollBy(0,Math.max(700,x.clientHeight*.9)));else await page.mouse.wheel(0,1100);await sleep(1200+Math.random()*900)}console.log('');return[...found].slice(0,limit)}
async function txt(page,selectors){for(let s of selectors){let x=page.locator(s).first();if(await x.count()){let v=await x.getAttribute('aria-label')||await x.textContent();if(v)return v.trim()}}return''}
async function webContacts(context,url){let out={emails:[],socials:{}};if(!url)return out;let p=await context.newPage();try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:25000});let pages=[p.url()],more=await p.locator('a[href]').evaluateAll(as=>as.map(a=>({h:a.href,t:a.textContent||''})).filter(x=>/contact|контакт|about|за нас/i.test(x.t)).map(x=>x.h).slice(0,2));pages.push(...more);for(let u of uniq(pages).slice(0,3)){if(u!==p.url())await p.goto(u,{waitUntil:'domcontentloaded',timeout:20000}).catch(()=>{});let html=await p.content(),emails=html.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[];out.emails.push(...emails.filter(x=>!/example\.|wixpress|sentry|schema|cloudflare/i.test(x)));let ls=await p.locator('a[href]').evaluateAll(as=>as.map(a=>a.href));for(let l of ls)for(let n of['facebook','instagram','linkedin','youtube','tiktok','twitter','x.com'])if(l.toLowerCase().includes(n))out.socials[n==='x.com'?'twitter':n]||=l}}catch{}finally{await p.close()}out.emails=uniq(out.emails).slice(0,5);return out}
async function place(context,url){let p=await context.newPage();try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await p.waitForTimeout(1800);let name=await txt(p,['h1','[role="main"] h1']);if(!name)return null;let phone=await txt(p,['button[data-item-id^="phone:tel:"]','[data-item-id^="phone"]']),address=await txt(p,['button[data-item-id="address"]','[data-item-id="address"]']),category=await txt(p,['button[jsaction*="category"]','button.DkEaL']),wl=p.locator('a[data-item-id="authority"]').first(),website=await wl.count()?await wl.getAttribute('href'):'',rating=parseFloat((await txt(p,['div.F7nice span[aria-hidden="true"]','[role="img"][aria-label*="звезд"]'])).replace(',','.'))||0,contacts=await webContacts(context,website);return{name,website,phone:phone.replace(/^Телефон:\s*/i,''),email:contacts.emails[0]||'',category,address:address.replace(/^Адрес:\s*/i,''),stars:rating,sourceUrl:p.url(),socials:contacts.socials}}finally{await p.close()}}
async function save(found){let token=await login(),loaded=await api('load',{},token),state=loaded.state||{},leads=Array.isArray(state.leads)?state.leads:[],seen=new Set(),digits=x=>String(x||'').replace(/\D/g,'');leads.forEach(l=>[l.website,digits(l.phone),(l.name||'')+'|'+(l.address||'')].filter(Boolean).forEach(x=>seen.add(x.toLowerCase())));let now=Date.now(),added=0;found.forEach((x,i)=>{let keys=[x.website,digits(x.phone),x.name+'|'+x.address].filter(Boolean).map(v=>v.toLowerCase());if(keys.some(k=>seen.has(k)))return;keys.forEach(k=>seen.add(k));leads.push({id:now+i,name:x.name,website:x.website,phone:x.phone,email:x.email,category:x.category,address:x.address,stars:x.stars,reviews:'',price:'',image:'',status:'unset',pipeline:'new',note:'',followup:'',tags:['Google Business'],extra:{'Google Maps / source URL':x.sourceUrl,Source:'Digital Eight Local Scraper',...x.socials},aiPhone:'',aiEmail:''});added++});await api('save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state,leads,saveScope:'shared'})},token);return added}
(async()=>{console.log('\n=== DIGITAL EIGHT GOOGLE BUSINESS SCRAPER ===\n');let query=await ask('Ниша + град или Google Maps URL: '),limit=Math.max(1,Math.min(500,parseInt(await ask('Брой бизнеси (примерно 100): '))||100));rl.close();let browser=await chromium.launch({headless:false,channel:'chrome'}).catch(()=>chromium.launch({headless:false})),context=await browser.newContext({locale:'bg-BG',viewport:{width:1400,height:900}});try{let p=await context.newPage(),urls=await links(p,query,limit);await p.close();let results=[];for(let i=0;i<urls.length;i++){process.stdout.write('\rОбработвам '+(i+1)+'/'+urls.length);let item=await place(context,urls[i]).catch(()=>null);if(item)results.push(item);await sleep(900+Math.random()*800)}console.log('\nЗаписвам в панела...');let added=await save(results);console.log('\nГОТОВО: '+added+' нови бизнеса. Дубликати: '+(results.length-added)+'\n')}catch(e){console.error('\nГРЕШКА: '+e.message+'\n');process.exitCode=1}finally{await browser.close()}})();
