const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),readline=require('readline');
const cfgPath=path.join(__dirname,'config.local.json');if(!fs.existsSync(cfgPath)){console.error('Стартирай първо SETUP SCRAPER.cmd');process.exit(1)}
const cfg=JSON.parse(fs.readFileSync(cfgPath,'utf8')),rl=readline.createInterface({input:process.stdin,output:process.stdout});
const ask=q=>new Promise(r=>rl.question(q,a=>r(a.trim()))),sleep=ms=>new Promise(r=>setTimeout(r,ms)),uniq=a=>[...new Set(a.filter(Boolean))];
async function api(action,opt={},token=''){let headers={...(opt.headers||{})};if(token)headers['X-D8-Auth']=token;let r=await fetch(cfg.dashboardUrl.replace(/\/$/,'')+'/api.php?action='+action,{...opt,headers}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||'Dashboard HTTP '+r.status);return d}
async function login(){return(await api('login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:cfg.username,password:cfg.password})})).authToken}
async function chooseFolder(){let token=await login(),loaded=await api('load',{},token),state=loaded.state||{},folders=Array.isArray(state.leadFolders)?state.leadFolders.filter(Boolean):[];console.log('\nПапка за новите leads:');folders.forEach((name,i)=>console.log('  '+(i+1)+'. '+name));console.log('  N. Създай нова папка');let answer=await ask('Избери номер или N: '),index=parseInt(answer,10)-1;if(Number.isInteger(index)&&folders[index])return folders[index];let name=answer&&!/^n$/i.test(answer)&&!/^new$/i.test(answer)?answer:await ask('Име на новата папка (например Зъболекари — София): ');name=name.trim().replace(/\s+/g,' ');if(!name)throw Error('Трябва да избереш или създадеш папка');return name}
async function links(page,query,limit){let url;if(/^https?:\/\//i.test(query)){let parsed=new URL(query);if(/(^|\.)google\.[^/]+$/i.test(parsed.hostname)&&parsed.pathname==='/search'){let search=parsed.searchParams.get('q')||parsed.searchParams.get('query');if(!search)throw Error('Google Search линкът няма дума за търсене');url='https://www.google.com/maps/search/'+encodeURIComponent(search)+'?hl=bg';console.log('Разпознах Google Search линк. Отварям Google Maps за: '+search)}else url=query}else url='https://www.google.com/maps/search/'+encodeURIComponent(query)+'?hl=bg';await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(3500);let consent=page.getByRole('button',{name:/accept all|приемам всички|съгласявам се/i});if(await consent.count())await consent.first().click().catch(()=>{});console.log('Ако има CAPTCHA, реши я в отворения Chrome. След това изчакай Google Maps резултатите.');try{await page.waitForSelector('a[href*="/maps/place/"]',{timeout:180000})}catch{throw Error('Не се появиха Google Maps бизнеси. Въведи ниша + град, например: зъболекари, София')}console.log('Резултатите са заредени. Започвам събирането...');let found=new Set(),still=0;while(found.size<limit&&still<8){let batch=await page.locator('a[href*="/maps/place/"]').evaluateAll(xs=>xs.map(x=>x.href));let before=found.size;batch.forEach(x=>found.add(x.split('&')[0]));still=found.size===before?still+1:0;process.stdout.write('\rНамерени бизнеси: '+found.size);let feed=page.locator('[role="feed"]').first();if(await feed.count())await feed.evaluate(x=>x.scrollBy(0,Math.max(700,x.clientHeight*.9)));else await page.mouse.wheel(0,1100);await sleep(1200+Math.random()*900)}console.log('');return[...found].slice(0,limit)}
async function txt(page,selectors){for(let s of selectors){let x=page.locator(s).first();if(await x.count()){let v=await x.getAttribute('aria-label')||await x.textContent();if(v)return v.trim()}}return''}
function decodeCfEmail(hex){try{let key=parseInt(hex.slice(0,2),16),out='';for(let i=2;i<hex.length;i+=2)out+=String.fromCharCode(parseInt(hex.slice(i,i+2),16)^key);return out}catch{return''}}
function cleanEmail(value){return String(value||'').trim().replace(/^mailto:/i,'').split('?')[0].replace(/^[<("' ]+|[>)"',;: ]+$/g,'').toLowerCase()}
function emailCandidates(text){let normalized=String(text||'').replace(/[\u200b-\u200d\ufeff]/g,'').replace(/\s*(?:\[at\]|\(at\)|\{at\}|\[кльомба\]|\(кльомба\))\s*/gi,'@').replace(/\s+(?:at|кльомба)\s+/gi,'@').replace(/\s*(?:\[dot\]|\(dot\)|\{dot\}|\[точка\]|\(точка\))\s*/gi,'.').replace(/\s+(?:dot|точка)\s+/gi,'.'),matches=normalized.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,24}/gi)||[];return matches.map(cleanEmail)}
function emailScore(email,host){let domain=email.split('@')[1]||'',local=email.split('@')[0]||'',score=0;if(domain===host||host.endsWith('.'+domain)||domain.endsWith('.'+host))score+=60;if(/^(info|contact|office|hello|sales|reception|booking|appointments?|admin|support|team|studio|shop|orders?)$/.test(local))score+=35;if(/noreply|no-reply|donotreply|privacy|abuse|example|test|demo/.test(local))score-=80;if(/sentry|wixpress|cloudflare|wordpress|schema|google|facebook/.test(domain))score-=70;if(/\.(png|jpg|jpeg|gif|svg|webp|css|js)$/i.test(email))score-=100;return score}
function usefulContactLink(item,origin){try{let u=new URL(item.href,origin);if(u.origin!==origin)return-1;let hay=(u.pathname+' '+(item.text||'')).toLowerCase(),score=0;if(/contact|contacts|contact-us|kontakt|kontakti|контакт/.test(hay))score+=100;if(/about|about-us|za-nas|за-нас|екип|team/.test(hay))score+=70;if(/impressum|company|office|location/.test(hay))score+=45;if(/\.(pdf|jpg|jpeg|png|zip)$/i.test(u.pathname))return-1;return score}catch{return-1}}
async function webContacts(context,url){
  let out={emails:[],socials:{}};
  if(!url)return out;
  let p=await context.newPage(),emailSet=new Set();
  try{
    if(!/^https?:\/\//i.test(url))url='https://'+url;
    await p.goto(url,{waitUntil:'domcontentloaded',timeout:30000});
    let home=new URL(p.url()),queue=[home.href],seen=new Set(),links=await p.locator('a[href]').evaluateAll(as=>as.map(a=>({href:a.href,text:(a.textContent||'').trim()}))).catch(()=>[]);
    links.map(x=>({url:x.href,score:usefulContactLink(x,home.origin)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).forEach(x=>{if(queue.length<5&&!queue.includes(x.url))queue.push(x.url)});
    for(let target of queue.slice(0,5)){
      let targetUrl;
      try{targetUrl=new URL(target,home.href);if(targetUrl.origin!==home.origin||seen.has(targetUrl.href))continue;seen.add(targetUrl.href)}catch{continue}
      if(p.url()!==targetUrl.href)await p.goto(targetUrl.href,{waitUntil:'domcontentloaded',timeout:22000}).catch(()=>null);
      await p.waitForTimeout(500);
      let payload=await p.evaluate(()=>({
        html:document.documentElement.innerHTML,
        text:document.body?document.body.innerText:'',
        mailtos:[...document.querySelectorAll('a[href^="mailto:"]')].map(a=>a.getAttribute('href')),
        cf:[...document.querySelectorAll('[data-cfemail]')].map(x=>x.getAttribute('data-cfemail')),
        links:[...document.querySelectorAll('a[href]')].map(a=>a.href)
      })).catch(()=>({html:'',text:'',mailtos:[],cf:[],links:[]}));
      emailCandidates(payload.html+' '+payload.text).forEach(x=>emailSet.add(x));
      payload.mailtos.map(cleanEmail).forEach(x=>emailSet.add(x));
      payload.cf.map(decodeCfEmail).map(cleanEmail).forEach(x=>emailSet.add(x));
      for(let link of payload.links)for(let name of['facebook','instagram','linkedin','youtube','tiktok','twitter','x.com'])if(link.toLowerCase().includes(name))out.socials[name==='x.com'?'twitter':name]||=link;
    }
    let host=home.hostname.toLowerCase().replace(/^www\./,'');
    out.emails=[...emailSet].filter(x=>x&&x.includes('@')&&emailScore(x,host)>-20).sort((a,b)=>emailScore(b,host)-emailScore(a,host)||a.localeCompare(b)).slice(0,8);
  }catch{}finally{await p.close()}
  return out
}
async function place(context,url){let p=await context.newPage();try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await p.waitForTimeout(1800);let name=await txt(p,['h1','[role="main"] h1']);if(!name)return null;let phone=await txt(p,['button[data-item-id^="phone:tel:"]','[data-item-id^="phone"]']),address=await txt(p,['button[data-item-id="address"]','[data-item-id="address"]']),category=await txt(p,['button[jsaction*="category"]','button.DkEaL']),wl=p.locator('a[data-item-id="authority"]').first(),website=await wl.count()?await wl.getAttribute('href'):'',rating=parseFloat((await txt(p,['div.F7nice span[aria-hidden="true"]','[role="img"][aria-label*="звезд"]'])).replace(',','.'))||0,contacts=await webContacts(context,website);return{name,website,phone:phone.replace(/^Телефон:\s*/i,''),email:contacts.emails[0]||'',allEmails:contacts.emails,category,address:address.replace(/^Адрес:\s*/i,''),stars:rating,sourceUrl:p.url(),socials:contacts.socials}}finally{await p.close()}}
async function save(found,folder){let token=await login(),loaded=await api('load',{},token),state=loaded.state||{},leads=Array.isArray(state.leads)?state.leads:[],leadFolders=Array.isArray(state.leadFolders)?state.leadFolders:[],seen=new Set(),digits=x=>String(x||'').replace(/\D/g,'');leads.forEach(l=>[l.website,digits(l.phone),(l.name||'')+'|'+(l.address||'')].filter(Boolean).forEach(x=>seen.add(x.toLowerCase())));let now=Date.now(),added=0;found.forEach((x,i)=>{let keys=[x.website,digits(x.phone),x.name+'|'+x.address].filter(Boolean).map(v=>v.toLowerCase());if(keys.some(k=>seen.has(k)))return;keys.forEach(k=>seen.add(k));leads.push({id:now+i,name:x.name,website:x.website,phone:x.phone,email:x.email,category:x.category,address:x.address,stars:x.stars,reviews:'',price:'',image:'',status:'unset',pipeline:'new',folder:folder,note:'',followup:'',tags:['Google Business'],extra:{'Google Maps / source URL':x.sourceUrl,Source:'Digital Eight Local Scraper','Email source':x.email?(x.website||x.sourceUrl):'','Alternative business emails':(x.allEmails||[]).slice(1).join(', '),...x.socials},aiPhone:'',aiEmail:''});added++});if(folder&&!leadFolders.some(x=>x.toLowerCase()===folder.toLowerCase()))leadFolders.push(folder);await api('save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state,leads,leadFolders,saveScope:'shared'})},token);return added}
(async()=>{console.log('\n=== DIGITAL EIGHT GOOGLE BUSINESS SCRAPER ===\n');let query=await ask('Ниша + град или Google Maps URL: '),folder=await chooseFolder(),limit=Number.MAX_SAFE_INTEGER;rl.close();console.log('Ще събера всички бизнеси, които Google Maps покаже...');let browser=await chromium.launch({headless:false,channel:'chrome'}).catch(()=>chromium.launch({headless:false})),context=await browser.newContext({locale:'bg-BG',viewport:{width:1400,height:900}});try{let p=await context.newPage(),urls=await links(p,query,limit);await p.close();let results=[];for(let i=0;i<urls.length;i++){process.stdout.write('\rОбработвам '+(i+1)+'/'+urls.length);let item=await place(context,urls[i]).catch(()=>null);if(item)results.push(item);await sleep(900+Math.random()*800)}let emailCount=results.filter(x=>x.email).length;console.log('\nНамерени бизнеси: '+results.length+' · с имейл за контакт: '+emailCount);console.log('\nЗаписвам в панела...');let added=await save(results,folder);console.log('\nГОТОВО: '+added+' нови бизнеса. Дубликати: '+(results.length-added)+'\n')}catch(e){console.error('\nГРЕШКА: '+e.message+'\n');process.exitCode=1}finally{await browser.close()}})();
