<?php
declare(strict_types=1);

function d8DecodeMime(string $value): string {
  if(function_exists('imap_mime_header_decode')){$parts=@imap_mime_header_decode($value);$out='';foreach($parts?:[] as $part){$charset=strtoupper((string)$part->charset);$text=(string)$part->text;if($charset&&$charset!=='DEFAULT'&&$charset!=='UTF-8'&&function_exists('iconv'))$text=(string)@iconv($charset,'UTF-8//IGNORE',$text);$out.=$text;}if($out!=='')return $out;}
  if(function_exists('iconv_mime_decode')){$decoded=@iconv_mime_decode($value,0,'UTF-8');if(is_string($decoded))return $decoded;}return $value;
}
function d8Pop3Line($conn): string {$line=fgets($conn,65536);if($line===false)throw new RuntimeException('POP3 връзката беше прекъсната');return rtrim($line,"\r\n");}
function d8Pop3Command($conn,string $command,bool $multi=false): string {if(fwrite($conn,$command."\r\n")===false)throw new RuntimeException('POP3 командата не беше изпратена');$first=d8Pop3Line($conn);if(strncmp($first,'+OK',3)!==0)throw new RuntimeException('POP3: '.$first);if(!$multi)return $first;$lines=[];while(true){$line=d8Pop3Line($conn);if($line==='.')break;if(strncmp($line,'..',2)===0)$line=substr($line,1);$lines[]=$line;}return implode("\r\n",$lines);}
function d8ParseMailHeaders(string $raw): array {$head=(string)((preg_split("/\r?\n\r?\n/",$raw,2)?:[])[0]??$raw);$head=preg_replace("/\r?\n[ \t]+/",' ',$head)??$head;$headers=[];foreach(preg_split("/\r?\n/",$head)?:[] as $line){$pos=strpos($line,':');if($pos===false)continue;$key=strtolower(trim(substr($line,0,$pos)));$value=trim(substr($line,$pos+1));$headers[$key]=isset($headers[$key])?$headers[$key].' '.$value:$value;}return $headers;}
function d8DecodeTransfer(string $body,string $encoding): string {$encoding=strtolower(trim($encoding));if($encoding==='base64'){$decoded=base64_decode(preg_replace('/\s+/','',$body)??$body,true);return is_string($decoded)?$decoded:'';}if($encoding==='quoted-printable')return quoted_printable_decode($body);return $body;}
function d8ExtractMessageBody(string $raw): string {$parts=preg_split("/\r?\n\r?\n/",$raw,2);$head=(string)($parts[0]??'');$body=(string)($parts[1]??'');$h=d8ParseMailHeaders($head);$type=strtolower((string)($h['content-type']??'text/plain'));$encoding=(string)($h['content-transfer-encoding']??'');if(preg_match('/boundary=(?:"([^"]+)"|([^;\s]+))/i',$type,$m)){$boundary=$m[1]?:$m[2];$fallback='';foreach(explode('--'.$boundary,$body) as $part){if(stripos($part,'content-disposition: attachment')!==false)continue;if(stripos($part,'content-type: text/plain')!==false){$text=d8ExtractMessageBody(ltrim($part,"\r\n"));if($text!=='')return $text;}if($fallback===''&&stripos($part,'content-type: text/html')!==false)$fallback=d8ExtractMessageBody(ltrim($part,"\r\n"));}return $fallback;}$body=d8DecodeTransfer($body,$encoding);if(strpos($type,'text/html')!==false){$body=preg_replace('/<\/?(?:p|div|li|tr|h[1-6])[^>]*>/i',"\n",$body)??$body;$body=preg_replace('/<br\s*\/?\s*>/i',"\n",$body)??$body;$body=html_entity_decode(strip_tags($body),ENT_QUOTES|ENT_HTML5,'UTF-8');}$body=preg_replace("/\r\n?/","\n",$body)??$body;$body=preg_replace("/\n{3,}/","\n\n",$body)??$body;return trim($body);}
function d8HeaderEmail(string $value): string {if(preg_match('/<([^>]+)>/',$value,$m))$value=$m[1];elseif(preg_match('/[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}/i',$value,$m))$value=$m[0];return strtolower(trim($value," \t\r\n\"'"));}
function d8ThreadIds(string $value): array {preg_match_all('/<[^>]+>/',$value,$m);return array_values(array_unique(array_map('strtolower',$m[0]??[])));}
function d8ReplyRecord(string $raw,string $mailbox,string $fallbackId): ?array {$h=d8ParseMailHeaders($raw);$email=d8HeaderEmail((string)($h['from']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL))return null;$ts=strtotime((string)($h['date']??''))?:time();return['email'=>$email,'subject'=>d8DecodeMime((string)($h['subject']??'')),'date'=>gmdate('c',$ts),'messageId'=>trim((string)($h['message-id']??$fallbackId)),'threadIds'=>d8ThreadIds((string)($h['in-reply-to']??'').' '.(string)($h['references']??'')),'mailbox'=>$mailbox,'body'=>d8ExtractMessageBody($raw)];}
function d8FetchReplyHeadersPop3(array $config): array {$smtp=is_array($config['smtp']??null)?$config['smtp']:[];$imap=is_array($config['imap']??null)?$config['imap']:[];$host=(string)($imap['host']??$smtp['host']??'mail.digitaleight.bg');$port=(int)($imap['pop3_port']??995);$user=strtolower((string)($imap['username']??$smtp['username']??''));$pass=(string)($imap['password']??$smtp['password']??'');if(!$user||!$pass)throw new RuntimeException('POP3 не е настроен');$errno=0;$error='';$conn=@stream_socket_client('ssl://'.$host.':'.$port,$errno,$error,20,STREAM_CLIENT_CONNECT);if(!$conn)throw new RuntimeException('POP3 връзката не успя: '.($error?:$errno));stream_set_timeout($conn,20);try{$hello=d8Pop3Line($conn);if(strncmp($hello,'+OK',3)!==0)throw new RuntimeException('POP3: '.$hello);d8Pop3Command($conn,'USER '.$user);d8Pop3Command($conn,'PASS '.$pass);$stat=d8Pop3Command($conn,'STAT');preg_match('/^\+OK\s+(\d+)/',$stat,$m);$count=(int)($m[1]??0);$start=max(1,$count-499);$rows=[];$since=time()-90*86400;for($id=$start;$id<=$count;$id++){$raw=d8Pop3Command($conn,'RETR '.$id,true);$row=d8ReplyRecord($raw,'INBOX (POP3)','pop3-'.$id);if(!$row||$row['email']===$user||strtotime($row['date'])<$since)continue;$rows[]=$row;}$GLOBALS['d8MailDiagnostics']=['transport'=>'POP3','mailbox'=>$user,'folders'=>1,'messages'=>count($rows)];return $rows;}finally{@fwrite($conn,"QUIT\r\n");@fclose($conn);}}
function d8FetchReplyHeaders(array $config): array {if(!function_exists('imap_open'))return d8FetchReplyHeadersPop3($config);$smtp=is_array($config['smtp']??null)?$config['smtp']:[];$imap=is_array($config['imap']??null)?$config['imap']:[];$host=(string)($imap['host']??$smtp['host']??'mail.digitaleight.bg');$port=(int)($imap['port']??993);$user=strtolower((string)($imap['username']??$smtp['username']??''));$pass=(string)($imap['password']??$smtp['password']??'');if(!$user||!$pass)throw new RuntimeException('IMAP не е настроен');$root='{'.$host.':'.$port.'/imap/ssl}';$conn=@imap_open($root.'INBOX',$user,$pass,OP_READONLY,1);if(!$conn)throw new RuntimeException('IMAP входът не успя: '.(imap_last_error()?:'неизвестна грешка'));try{$mailboxes=[$root.'INBOX'];foreach(@imap_getmailboxes($conn,$root,'*')?:[] as $item){$full=(string)($item->name??'');$label=strtolower(str_replace($root,'',$full));if(!$full||preg_match('~(^|[./])(sent|sent items|trash|deleted|drafts|draft)$~i',$label))continue;if(!in_array($full,$mailboxes,true))$mailboxes[]=$full;}$rows=[];$seen=[];$since=time()-90*86400;foreach($mailboxes as $mailbox){if(!@imap_reopen($conn,$mailbox,OP_READONLY))continue;$ids=imap_search($conn,'SINCE "'.date('d-M-Y',$since).'"')?:[];foreach(array_slice($ids,-500) as $id){$header=(string)@imap_fetchheader($conn,(int)$id,FT_PREFETCHTEXT);$body=(string)@imap_body($conn,(int)$id,FT_PEEK);$row=d8ReplyRecord($header."\r\n".$body,str_replace($root,'',$mailbox),'imap-'.$mailbox.'-'.$id);if(!$row||$row['email']===$user)continue;$key=strtolower($row['messageId'].'|'.$row['email']);if(isset($seen[$key]))continue;$seen[$key]=true;$rows[]=$row;}}$GLOBALS['d8MailDiagnostics']=['transport'=>'IMAP','mailbox'=>$user,'folders'=>count($mailboxes),'messages'=>count($rows)];return $rows;}finally{imap_close($conn);}}
function d8SubjectKey(string $subject): string {$subject=d8DecodeMime($subject);$subject=preg_replace('/^\s*((re|fw|fwd|отг|преп)\s*:\s*)+/iu','',$subject)??$subject;return mb_strtolower(trim(preg_replace('/\s+/u',' ',$subject)??$subject),'UTF-8');}
function d8ApplyReplies(array &$state,array $replies): int {$updated=0;$matched=[];foreach($state['leads']??[] as &$lead){$email=strtolower(trim((string)($lead['email']??'')));$out=is_array($lead['outreach']??null)?$lead['outreach']:[];$sentAt=(string)($out['sentAt']??'');if(!$sentAt&&!in_array((string)($out['status']??''),['sent','replied'],true))continue;$sentTs=$sentAt?strtotime($sentAt):0;$sentId=strtolower(trim((string)($out['sentMessageId']??'')));$subjectKey=d8SubjectKey((string)($out['subject']??''));$candidates=[];foreach($replies as $idx=>$reply){$direct=$email!==''&&strtolower((string)$reply['email'])===$email;$thread=$sentId!==''&&in_array($sentId,$reply['threadIds']??[],true);$subject=$subjectKey!==''&&d8SubjectKey((string)($reply['subject']??''))===$subjectKey;if(!$direct&&!$thread&&!$subject)continue;$replyTs=strtotime((string)($reply['date']??''))?:0;if($sentTs&&$replyTs&&$replyTs<$sentTs-900)continue;$candidates[$idx]=$reply;}if(!$candidates)continue;$seen=is_array($out['replyMessageIds']??null)?$out['replyMessageIds']:[];$messages=is_array($out['replyMessages']??null)?$out['replyMessages']:[];foreach($candidates as $idx=>$reply){$id=(string)$reply['messageId'];$stored=false;foreach($messages as $message){if((string)($message['messageId']??'')===$id){$stored=true;break;}}if($stored)continue;$seen[]=$id;$messages[]=['messageId'=>$id,'subject'=>$reply['subject'],'date'=>$reply['date'],'body'=>(string)($reply['body']??''),'mailbox'=>$reply['mailbox']??'INBOX','from'=>$reply['email']];$out['status']='replied';$out['replyAt']=$reply['date'];$out['replySubject']=$reply['subject'];$out['replyMailbox']=$reply['mailbox']??'INBOX';$out['replyCount']=(int)($out['replyCount']??0)+1;$out['nextFollowupAt']='';$out['followupStatus']='stopped';$out['updatedAt']=gmdate('c');$lead['followup']='';$updated++;$matched[$idx]=true;}$out['replyMessages']=array_slice($messages,-30);$out['replyMessageIds']=array_slice(array_values(array_unique($seen)),-30);$lead['outreach']=$out;}unset($lead);$GLOBALS['d8MailDiagnostics']['matchedMessages']=count($matched);return $updated;}
function d8MailDiagnostics(): array {return is_array($GLOBALS['d8MailDiagnostics']??null)?$GLOBALS['d8MailDiagnostics']:[];}
